In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings(action="ignore")

In [3]:
# load the dataset
df_raw=pd.read_excel("Airlines Flights Dataset - Processed.xlsx")

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10682 entries, 0 to 10681
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Airline            10682 non-null  object
 1   Date_of_Journey    10682 non-null  object
 2   Source             10682 non-null  object
 3   Destination        10682 non-null  object
 4   Route              10682 non-null  object
 5   Dep_Time           10682 non-null  object
 6   Arrival Time       10682 non-null  object
 7   Duration(in mins)  10682 non-null  int64
 8   Total Stops        10682 non-null  object
 9   Additional_Info    10682 non-null  object
 10  Ticket Price       10682 non-null  int64
 11  Cabin Class        10682 non-null  object
dtypes: int64(2), object(10)
memory usage: 1001.6+ KB

In [5]:
df_raw.sample(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival Time,Duration(in mins),Total Stops,Additional_Info,Ticket Price,Cabin Class
2194,Jet Airways,21/05/2019,Banglore,Delhi,BLR → DEL,06:00,08:45:00,165,Non-Stop,No info,7229,General
6943,Air India,9/05/2019,Banglore,Delhi,BLR → DEL,13:20,16:10:00,170,Non-Stop,No info,6121,General
4155,IndiGo,9/05/2019,Mumbai,Hyderabad,BOM → HYD,16:55,18:25:00,90,Non-Stop,No info,4784,General
592,Jet Airways,21/04/2019,Banglore,Delhi,BLR → DEL,07:10,10:10:00,180,Non-Stop,In-flight meal not included,6144,General
7048,GoAir,6/06/2019,Delhi,Cochin,DEL → BOM → COK,14:25,19:35:00,310,1 Stop,No info,7870,General

In [6]:
df_raw.shape

(10682, 12)

In [7]:
# null values 
df_raw.isnull().sum()

Airline              0
Date_of_Journey      0
Source               0
Destination          0
Route                0
Dep_Time             0
Arrival Time         0
Duration(in mins)    0
Total Stops          0
Additional_Info      0
Ticket Price         0
Cabin Class          0
dtype: int64

----

In [8]:
df=df_raw[["Airline","Source","Destination","Cabin Class","Ticket Price"]]

In [9]:
df.shape

(10682, 5)

---

In [10]:
df[:2]

     Airline    Source Destination Cabin Class  Ticket Price
0     IndiGo  Banglore   New Delhi     General          3897
1  Air India   Kolkata    Banglore     General          7662

In [11]:
# defining X and y
x=df.drop("Ticket Price",axis=1)
y=df["Ticket Price"]

In [12]:
x[:2]

     Airline    Source Destination Cabin Class
0     IndiGo  Banglore   New Delhi     General
1  Air India   Kolkata    Banglore     General

In [13]:
y[:1]

0    3897
Name: Ticket Price, dtype: int64

In [14]:
# label encoding
from sklearn.preprocessing import LabelEncoder

In [15]:
# call and assign
le=LabelEncoder()

In [16]:
le

LabelEncoder()

In [17]:
x.dtypes

Airline        object
Source         object
Destination    object
Cabin Class    object
dtype: object

In [18]:
# apply on X
for col in x:
    x[col] = le.fit_transform(x[col])

In [19]:
x[:2]

   Airline  Source  Destination  Cabin Class
0        3       0            5            3
1        1       3            0            3

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size = 0.2, random_state = 42)

In [22]:
# view
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((8545, 4), (2137, 4), (8545,), (2137,))

---

In [23]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
model = RandomForestRegressor()

In [25]:
model

RandomForestRegressor()

In [26]:
model.fit(x_train, y_train)

RandomForestRegressor()

In [27]:
model.score(x_train, y_train)

0.8844397612158635

In [28]:
model.score(x_test, y_test)

0.8801052523120338

----

In [29]:
y_pred = model.predict(x_test)

In [30]:
y_pred

array([16613.42745101,  5778.33904183,  9265.92811996, ...,
        6503.62216552, 12039.88853404, 12039.88853404])

In [31]:
from sklearn.metrics import r2_score

In [32]:
r2_score(y_test, y_pred)

0.8801052523120338

In [33]:
from joblib import dump

In [34]:
dump(model, "airline_price_model.pkl")

['airline_price_model.pkl']

In [35]:
# Dump
dump(model,'model.joblib')
dump(x.columns,'columns.joblib')
dump(x,'data.joblib')

['data.joblib']

In [36]:
from sklearn.preprocessing import LabelEncoder
from joblib import dump

encoders = {}

x = df.drop("Ticket Price",axis=1)

for col in x.columns:
    
    le = LabelEncoder()

    x[col] = le.fit_transform(x[col])

    encoders[col] = le

dump(encoders,"encoders.joblib")

['encoders.joblib']